schema_version = 1
uuid = "550e8400-e29b-41d4-a716-446655440000"

[profile]
title = "血DK循环"
description = "测试使用。"
unit_class = "DEATHKNIGHT"
unit_class_id = 6
unit_spec = 1

[[conditions]]
title = "符文能量"
plugin = "player_primary_power@1.0"
[conditions.plugin_args]
max_power = 120

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 1
y = 2
[[conditions]]
title = "符文数量"
plugin = "spec_dk_rune@1.0"
# 无参数

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 2
y = 2
[[conditions]]
title = "血沸充能"
plugin = "spell_charges@1.0"
[conditions.plugin_args]
spell_ids = [50841, 50842]
max_charges = 2

[conditions.layout]
output_type = "value_bar"

[[conditions.layout.regions]]
x = 1
width = 2
[[conditions]]
title = "血沸高亮"
plugin = "spell_overlay@1.0"
[conditions.plugin_args]
spell_ids = [50841, 50842]

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 3
y = 2
[[conditions]]
title = "公共冷却"
plugin = "spell_gcd@1.0"

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 4
y = 2
[[conditions]]
title = "死神的抚摩冷却"
plugin = "spell_cooldown@1.0"
[conditions.plugin_args]
spell_ids = [195292]
ignore_gcd = true

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 5
y = 2
[[conditions]]
title = "玩家血量百分比"
plugin = "player_health_pct@1.0"
# 无参数

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 6
y = 2
[[conditions]]
title = "灵界打击可用"
plugin = "spell_usable@1.0"
[conditions.plugin_args]
spell_ids = [49998]

[conditions.layout]
output_type = "cell"

[[conditions.layout.regions]]
x = 7
y = 2
[[macros]]
name = "灵界打击"
macro_text = "/cast [@target] 灵界打击"
key = "CTRL-NUMPAD1"
bind_key = true

[[macros]]
name = "血液沸腾"
macro_text = "/cast 血液沸腾"
key = "CTRL-NUMPAD2"
bind_key = true

[[macros]]
name = "死神的抚摩"
macro_text = "/cast 死神的抚摩"
key = "CTRL-NUMPAD3"
bind_key = true

[[macros]]
name = "心脏打击"
macro_text = "/cast 心脏打击"
key = "CTRL-NUMPAD4"
bind_key = true

[[rotation]]
annotate = "血量低于50%，就打灵界打击回血"
condition = "(玩家血量百分比 < 50) and 灵界打击可用 and (符文能量>=40)"
macro = "灵界打击"

[[rotation]]
annotate = "打高亮血沸"
condition = "血沸高亮 and (血沸充能>=1)"
macro = "血液沸腾"

[[rotation]]
annotate = "死神的抚摩，好了就用"
condition = "(死神的抚摩冷却==0)"
macro = "死神的抚摩"

[[rotation]]
annotate = "能量溢出，打灵打"
condition = "灵界打击可用 and (符文能量>=100)"
macro = "灵界打击"

[[rotation]]
annotate = "有符文就填充心脏打击"
condition = "符文数量>=1"
macro = "心脏打击"

[[rotation]]
annotate = "兜底规则"
condition = ""
macro = "Idle"
