schema_version = 1
uuid = "15a37eea-e9f2-59cc-8e83-bbfd03fe866e"

[profile]
title = "死亡骑士-鲜血"
description = "作者：liantian-cn"
unit_class = "DEATHKNIGHT"
unit_class_id = 6
unit_spec = 1

[[conditions]]
title = "插件启用"
plugin = "enable@dev"

[[conditions]]
title = "玩家战斗中"
plugin = "player_in_combat@dev"

[[conditions]]
title = "玩家施法进度"
plugin = "player_cast_progress@dev"

[[conditions]]
title = "玩家正在蓄力"
plugin = "player_is_empowering@dev"

[[conditions]]
title = "目标存在"
plugin = "target_is_exists@dev"

[[conditions]]
title = "目标存活"
plugin = "target_is_alive@dev"

[[conditions]]
title = "目标可攻击"
plugin = "target_can_attack@dev"

[[conditions]]
title = "目标可协助"
plugin = "target_can_assist@dev"

[[conditions]]
title = "玩家生命值"
plugin = "player_health_pct@dev"
[conditions.plugin_args]
use_predicted = true

[[conditions]]
title = "符文能量"
plugin = "spec_power_runic_power@dev"
[conditions.plugin_args]
max_power = 120

[[conditions]]
title = "焦点可打断"
plugin = "focus_cast_interruptible@dev"

[[conditions]]
title = "心灵冰冻冷却"
plugin = "spell_cooldown@dev"
[conditions.plugin_args]
spell_ids = [47528]
ignore_gcd = true

[[conditions]]
title = "焦点存在"
plugin = "focus_is_exists@dev"

[[conditions]]
title = "焦点存活"
plugin = "focus_is_alive@dev"

[[conditions]]
title = "焦点可攻击"
plugin = "focus_can_attack@dev"

[[conditions]]
title = "焦点可协助"
plugin = "focus_can_assist@dev"

[[conditions]]
title = "目标可打断"
plugin = "target_cast_interruptible@dev"

[[conditions]]
title = "白骨之盾剩余时间"
plugin = "aura_player_buff_duration@dev"
[conditions.plugin_args]
aura_ids = [195181]
duration = 30
width = 8
player_only = true

[[conditions]]
title = "白骨之盾层数"
plugin = "aura_player_buff_stacks@dev"
[conditions.plugin_args]
aura_ids = [195181]
max_value = 12
min_value = 0
width = 3
player_only = true

[[conditions]]
title = "死神印记冷却"
plugin = "spell_cooldown@dev"
[conditions.plugin_args]
spell_ids = [439843]
ignore_gcd = true

[[conditions]]
title = "符文刃舞冷却"
plugin = "spell_cooldown@dev"
[conditions.plugin_args]
spell_ids = [49028]
ignore_gcd = true

[[conditions]]
title = "爆发开启"
plugin = "in_burst@dev"

[[conditions]]
title = "玩家正在移动"
plugin = "player_is_moving@dev"

[[conditions]]
title = "符文"
plugin = "spec_power_rune@dev"

[[conditions]]
title = "死神的抚摩冷却"
plugin = "spell_cooldown@dev"
[conditions.plugin_args]
spell_ids = [195292]
ignore_gcd = true

[[conditions]]
title = "圣光潜力冷却就绪"
plugin = "item_cooldown_ready@dev"
[conditions.plugin_args]
item_id = 241308

[[conditions]]
title = "玩家有破灭"
plugin = "player_has_buff@dev"
[conditions.plugin_args]
buff_ids = [441426, 447954, 441424, 441378, 441416]
player_only = true

[[conditions]]
title = "血液沸腾充能"
plugin = "spell_charges@dev"
[conditions.plugin_args]
spell_ids = [50842]
max_charges = 2
width = 1

[[conditions]]
title = "目标有血之疫病"
plugin = "target_has_debuff@dev"
[conditions.plugin_args]
aura_ids = [55078]

[[conditions]]
title = "目标在灵界打击范围内"
plugin = "target_in_range@dev"
[conditions.plugin_args]
spell_id = 49998

[[conditions]]
title = "目标生命值"
plugin = "target_health_pct@dev"
[conditions.plugin_args]
use_predicted = true

[[conditions]]
title = "枯萎凋零充能"
plugin = "spell_charges@dev"
[conditions.plugin_args]
spell_ids = [43265]
max_charges = 2
width = 1

[[conditions]]
title = "玩家有赤色天灾"
plugin = "player_has_buff@dev"
[conditions.plugin_args]
buff_ids = [81141, 81136]
player_only = true

[[conditions]]
title = "玩家有枯萎凋零"
plugin = "player_has_buff@dev"
[conditions.plugin_args]
buff_ids = [188290]
player_only = true

[[conditions]]
title = "玩家有沸点"
plugin = "player_has_buff@dev"
[conditions.plugin_args]
buff_ids = [1265790, 1265982, 1265968]
player_only = true

[[conditions]]
title = "玩家有午夜舞步"
plugin = "player_has_buff@dev"
[conditions.plugin_args]
buff_ids = [1264351, 1264405, 1264568, 1264407]
player_only = true

[[conditions]]
title = "亡者复生冷却"
plugin = "spell_cooldown@dev"
[conditions.plugin_args]
spell_ids = [46585]
ignore_gcd = true

[[conditions]]
title = "打断黑名单图标"
plugin = "interrupt_blacklist_icons@dev"

[[macros]]
name = "灵界打击"
macro_text = "/cast 灵界打击"

[[macros]]
name = "焦点心灵冰冻"
macro_text = "/cast [@focus] 心灵冰冻"

[[macros]]
name = "目标心灵冰冻"
macro_text = "/cast [@target] 心灵冰冻"

[[macros]]
name = "死神印记"
macro_text = "/cast 死神印记"

[[macros]]
name = "符文刃舞"
macro_text = "/cast 符文刃舞"

[[macros]]
name = "精髓分裂"
macro_text = "/cast 精髓分裂"

[[macros]]
name = "死神的抚摩"
macro_text = "/cast 死神的抚摩"

[[macros]]
name = "圣光潜力"
macro_text = "/cast item:241308\n/cast item:241309"

[[macros]]
name = "血液沸腾"
macro_text = "/cast 血液沸腾"

[[macros]]
name = "枯萎凋零"
macro_text = "/cast [@player] 枯萎凋零"

[[macros]]
name = "心脏打击"
macro_text = "/cast 心脏打击"

[[macros]]
name = "亡者复生"
macro_text = "/cast 亡者复生"

[[rotation]]
condition = "not 插件启用"
macro = "Idle"

[[rotation]]
condition = "not 玩家战斗中"
macro = "Idle"

[[rotation]]
condition = "玩家施法进度 > 0"
macro = "Idle"

[[rotation]]
condition = "玩家正在蓄力"
macro = "Idle"

[[rotation]]
condition = "not (目标存在 and 目标存活 and 目标可攻击 and not 目标可协助)"
macro = "Idle"

[[rotation]]
condition = "玩家生命值 <= 55 and 符文能量 >= 42"
macro = "灵界打击"

[[rotation]]
condition = "焦点可打断 and 心灵冰冻冷却 == 0 and (焦点存在 and 焦点存活 and 焦点可攻击 and not 焦点可协助)"
macro = "焦点心灵冰冻"

[[rotation]]
condition = "目标可打断 and 心灵冰冻冷却 == 0"
macro = "目标心灵冰冻"

[[rotation]]
condition = "(白骨之盾剩余时间 <= 5 or 白骨之盾层数 <= 5) and (死神印记冷却 == 0)"
macro = "死神印记"

[[rotation]]
condition = "符文刃舞冷却 == 0 and 爆发开启 and not 玩家正在移动"
macro = "符文刃舞"

[[rotation]]
condition = "(白骨之盾剩余时间 <= 5 or 白骨之盾层数 <= 5) and (符文 >= 3)"
macro = "精髓分裂"

[[rotation]]
condition = "(白骨之盾剩余时间 <= 5 or 白骨之盾层数 <= 5) and (死神的抚摩冷却 == 0)"
macro = "死神的抚摩"

[[rotation]]
condition = "圣光潜力冷却就绪 and 爆发开启 and not 玩家正在移动"
macro = "圣光潜力"

[[rotation]]
condition = "符文 >= 2 and 玩家有破灭"
macro = "精髓分裂"

[[rotation]]
condition = "血液沸腾充能 >= 1 and not 目标有血之疫病 and 目标在灵界打击范围内"
macro = "血液沸腾"

[[rotation]]
condition = "死神印记冷却 == 0 and 目标生命值 >= 20"
macro = "死神印记"

[[rotation]]
condition = "枯萎凋零充能 == 2 and 玩家有赤色天灾"
macro = "枯萎凋零"

[[rotation]]
condition = "not 玩家有枯萎凋零 and 枯萎凋零充能 == 2 and not 玩家正在移动"
macro = "枯萎凋零"

[[rotation]]
condition = "not 玩家有枯萎凋零 and 玩家有赤色天灾 and not 玩家正在移动"
macro = "枯萎凋零"

[[rotation]]
condition = "血液沸腾充能 >= 1 and 玩家有沸点"
macro = "血液沸腾"

[[rotation]]
condition = "符文能量 >= 100"
macro = "灵界打击"

[[rotation]]
condition = "玩家有午夜舞步 and 符文 >= 1"
macro = "心脏打击"

[[rotation]]
condition = "符文 >= 3"
macro = "心脏打击"

[[rotation]]
condition = "死神的抚摩冷却 == 0 and 白骨之盾层数 <= 9"
macro = "死神的抚摩"

[[rotation]]
condition = "亡者复生冷却 == 0"
macro = "亡者复生"

[[rotation]]
condition = "血液沸腾充能 == 2"
macro = "血液沸腾"

[[rotation]]
condition = "符文 >= 1 and not 玩家有破灭"
macro = "心脏打击"

[[rotation]]
condition = "血液沸腾充能 >= 1"
macro = "血液沸腾"

[[rotation]]
condition = ""
macro = "Idle"
